package web

import (
	"bytes"
	"embed"
	"io/fs"
	"net/http"
	"net/http/httputil"
	"net/url"
	"path"
	"strings"
	"time"
)

const (
	indexAssetName    = "index.html"
	fallbackAssetName = "index-fallback.html"
)

// Production assets are generated by Vite and embedded into bridgectl.
// The tracked fallback keeps clean-checkout Go tests buildable.
//
//go:embed prebuilt/build/*
var embeddedAssets embed.FS

// AssetOptions configures explicit Vite development proxying.
type AssetOptions struct {
	DevServerURL string
}

// NewAssetHandler serves the generated console or the tracked fallback asset.
func NewAssetHandler(options ...AssetOptions) http.Handler {
	assets, err := fs.Sub(embeddedAssets, "prebuilt/build")
	if err != nil {
		return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			http.Error(w, "console assets unavailable", http.StatusInternalServerError)
		})
	}
	devURL := ""
	if len(options) > 0 {
		devURL = options[0].DevServerURL
	}
	return newAssetHandler(assets, devURL)
}

func newAssetHandler(assets fs.FS, devServerURLs ...string) http.Handler {
	var devProxy *httputil.ReverseProxy
	if len(devServerURLs) > 0 {
		devProxy = newDevProxy(devServerURLs[0])
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if devProxy != nil && isDevAssetPath(r.URL.Path) {
			devProxy.ServeHTTP(w, r)
			return
		}
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			w.Header().Set("Allow", "GET, HEAD")
			w.WriteHeader(http.StatusMethodNotAllowed)
			return
		}

		rawPath := strings.TrimPrefix(r.URL.Path, "/")
		requested := ""
		for _, segment := range strings.Split(rawPath, "/") {
			if segment == ".." {
				break
			}
		}
		if !strings.Contains(rawPath, "..") {
			requested = strings.TrimPrefix(path.Clean("/"+r.URL.Path), "/")
		}
		if requested == "." || requested == "" {
			requested = indexAssetName
		}

		if requested != "" {
			if data, err := fs.ReadFile(assets, requested); err == nil {
				writeAsset(w, r, requested, data)
				return
			}
		}

		indexName := fallbackAssetName
		if _, err := fs.Stat(assets, indexAssetName); err == nil {
			indexName = indexAssetName
		}
		data, err := fs.ReadFile(assets, indexName)
		if err != nil {
			http.Error(w, "console asset not found", http.StatusNotFound)
			return
		}
		writeAsset(w, r, indexName, data)
	})
}

func newDevProxy(rawURL string) *httputil.ReverseProxy {
	parsed, err := url.Parse(rawURL)
	if err != nil || parsed.Scheme != "http" || parsed.Hostname() == "" {
		return nil
	}
	if parsed.Hostname() != loopbackAddress && parsed.Hostname() != ipv6Loopback {
		return nil
	}
	return httputil.NewSingleHostReverseProxy(parsed)
}

func isDevAssetPath(path string) bool {
	return path == "/" || path == "/@vite/client" ||
		strings.HasPrefix(path, "/@vite/") ||
		strings.HasPrefix(path, "/@react-refresh") ||
		strings.HasPrefix(path, "/src/") ||
		strings.HasPrefix(path, "/node_modules/")
}

func writeAsset(w http.ResponseWriter, r *http.Request, name string, data []byte) {
	if strings.HasPrefix(name, "assets/") {
		w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
	} else {
		w.Header().Set("Cache-Control", "no-store")
	}
	http.ServeContent(w, r, name, time.Time{}, bytes.NewReader(data))
}
